# Generated by Django 4.1.7 on 2023-03-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_client_address_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
