# Generated by Django 4.1.7 on 2023-03-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_storage_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='available_units',
            field=models.IntegerField(default=0),
        ),
    ]
