# Generated by Django 4.1.7 on 2023-03-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_storage_available_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='available_units',
            new_name='no_of_units',
        ),
    ]
