# Generated by Django 4.1.7 on 2023-03-27 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0004_rename_available_units_storage_no_of_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to=settings.AUTH_USER_MODEL),
        ),
    ]
