# Generated by Django 4.1.7 on 2023-03-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_goods_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='no_of_units',
            field=models.IntegerField(null=True),
        ),
    ]
